version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: realtime_chat_and_threads_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: realtime_chat_and_threads_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6450:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: